[package]
name = "philia"
version = "0.6.1"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
serde_json = "1.0.89"
const_format = "0.2.30"
serde = { version = "1.0.148", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["blocking"] }