[package]
name = "philia"
version = "0.5.0"
edition = "2021"

[dependencies]
serde_json = "1.0.89"
const_format = "0.2.30"
serde = { version = "1.0.148", features = ["derive"] }
chrono = { version = "0.4.23", features = ["serde"] }
reqwest = { version = "0.11.13", features = ["blocking"] }