[package]
name = "philia"
version = "0.5.0"
edition = "2021"

[dependencies]
futures = "0.3.25"
serde = "1.0.148"
serde_json = "1.0.89"
serde_derive = "1.0.148"
const_format = "0.2.30"
chrono = { version = "0.4.23", features = ["serde"] }
reqwest = { version = "0.11.13", features = ["blocking"] }